version: "3.9"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: initial-password
      MYSQL_DATABASE: chat_app
    volumes:
      - db-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
  server:
    # build: ./server
    image: gracesta/chatapp-go-server
    ports:
      - "8888:8888"
  client:
    # build: .
    image: gracesta/chatapp-go-client
    entrypoint: ["./client"]
    command: ["--ip", "server", "--client_port", "7777"]
    ports:
      - "80:7777"
    depends_on:
      - db
      - server
    links:
      - server
    
volumes:
  db-data:      
